version: "3.8"
services:
  api:
    build: ./Nodepractice
    container_name: docker_nodepractice_demo
    ports:
      - '4000:4000'
    volumes:
      - ./docker_nodepractice_demo:/app
      - ./app/node_modules
  myblog:
    build: ./reactpracticeio
    container_name: docker_reactpractice_demo
    ports:
      - '3000:3000'
    volumes:
      - ./reactpracticeio:/app
      - ./app/node_modules
    stdin_open: true